### ISSUE TITLE
TypeError Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#103]
https://app.getsentry.com/nossas-cidades/usuario-final/issues/140213976/

```
TypeError: Cannot read property 'querySelectorAll' of null
  at _getLinks (/wysihtml/wysihtml-toolbar.min.js:10:8892)
  at constructor (/wysihtml/wysihtml-toolbar.min.js:10:8281)
  at new d.constructor (/wysihtml/wysihtml-toolbar.min.js:5:13552)
  at handleBeforeLoad (/wysihtml/wysihtml-toolbar.min.js:10:3018)
  at fire (/wysihtml/wysihtml-toolbar.min.js:5:20334)
...
(4 additional frame(s) were not displayed)
```

**Comment by lpirola** [comment]
These kind of bug its not related with our codebase.
