### ISSUE TITLE
Dificuldades em inserir um link em imagens - Slate Editor

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1070]
Error: Unable to find a DOM node for "1320". This is often because of forgetting to add `props.attribute...

https://sentry.io/organizations/nossas/issues/1035213078/?referrer=github_plugin

```
Error: Unable to find a DOM node for "1320". This is often because of forgetting to add `props.attributes` to a custom component.
  at findDOMNode$1 (../node_modules/slate-editor/node_modules/slate-react/lib/slate-react.es.js:1122:1)
  at findDOMPoint (../node_modules/slate-editor/node_modules/slate-react/lib/slate-react.es.js:1138:1)
  at findDOMRange (../node_modules/slate-editor/node_modules/slate-react/lib/slate-react.es.js:1179:1)
  at updateSelection (../node_modules/slate-editor/node_modules/slate-react/lib/slate-react.es.js:1663:1)
  at componentDidUpdate (../node_modules/slate-editor/node_modules/slate-react/lib/slate-react.es.js:1836:1)
...
(6 additional frame(s) were not displayed)
```

**Comment by igr-santos** [comment]
Esse BUG está dividio em 2 problemas:

* Problema na UX quando acontece o processo de salvar edição da widget de conteúdo:
* * Apesar de salvar no server, não existe dica visual que informe que o procedimento aconteceu com sucesso.

* Problema no slate-editor plugin de imagem, ao tentar mover o cursor para esquerda ou direita próximo a uma imagem, recebo uma exceção e a aplicação falha.

**Comment by igr-santos** [comment]
O problema no slate-editor vou seguir detalhando nesta issue: https://github.com/nossas/slate-editor/issues/82 que está no repositório do projeto.
