### ISSUE TITLE
Invariant Violation: The operation 'metricsCommunity' wrapping 'Component' is expecting a variable: 'communityId' but ...

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1315]
https://sentry.io/organizations/nossas/issues/1501964359/?referrer=github_plugin

```
Invariant Violation: The operation 'metricsCommunity' wrapping 'Component' is expecting a variable: 'communityId' but it was not found in the props passed to 'Apollo(Component)'
  at invariant$1 (../node_modules/invariant/browser.js:34:1)
  at calculateOptions (../node_modules/react-apollo/react-apollo.browser.umd.js:531:1)
  at setInitialProps (../node_modules/react-apollo/react-apollo.browser.umd.js:555:1)
  at componentWillMount (../node_modules/react-apollo/react-apollo.browser.umd.js:391:1)
  at $f (../node_modules/react-dom/cjs/react-dom.production.min.js:2955:1)
...
(9 additional frame(s) were not displayed)
```

**Comment by lpirola** [comment]
corrigido com atualização da infraestrutura, problema estava relacionado a performance.
