### ISSUE TITLE
Problemas na submissão de formulários da Visão Pública do BONDE "iOS / Safari"

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#1524]
Após as últimas atualizações, por existir uma necessidade de acessar uma parte da plataforma em sua versão mobile, foram feitos alguns testes no acesso do admin-canary e na visão pública do BONDE a partir de dispositivos móveis.

Após acessar a visão pública de um dispositivo iOS com navegador Safari encontramos um erro na submissão do formulário.

```
iPhone SE
iOS: 15.1
Safari: 15.1
```
Debugando o erro junto a @gloriateodoro descobrimos que ao submeter o formulário a partir deste dispositivo temos um erro na ação criada dentro da api de ativistas, hoje conectada por remote schema ao hasura.

Formulários testados

- PLIP (erro)
- Pressão por e-mail (sucesso)
- Formulário (sucesso)
- Doação (sucesso)

**Comment by igr-santos** [comment]
Resultado Formulário PLIP na API:

```
previous error TypeError: Cannot read property 'insert_activists' of undefined
    at /home/igrsantos/Repos/nossas/bonde/apis/api-graphql/packages/activists-api/src/graphql-api/activists.ts:116:15
    at step (/home/igrsantos/Repos/nossas/bonde/apis/api-graphql/packages/activists-api/src/graphql-api/activists.ts:33:23)
    at Object.next (/home/igrsantos/Repos/nossas/bonde/apis/api-graphql/packages/activists-api/src/graphql-api/activists.ts:14:53)
    at fulfilled (/home/igrsantos/Repos/nossas/bonde/apis/api-graphql/packages/activists-api/src/graphql-api/activists.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
