### ISSUE TITLE
Exception found after release new editor

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#254]
TypeError: _reactDom2.default.findDOMNode(...) is null

https://sentry.io/nossas-cidades/usuario-final/issues/178787592/

```
TypeError: _reactDom2.default.findDOMNode(...) is null
  at disableEditor (./app/scripts/Widget/plugins/ContentWidget/OldEditorContentWidget.js:63:4)
  at save (./app/scripts/Widget/plugins/ContentWidget/OldEditorContentWidget.js:102:4)
  at handleEscapePress (./app/scripts/Widget/plugins/ContentWidget/OldEditorContentWidget.js:72:6)
```

**Comment by lpirola** [comment]
We must be worried about this?

**Comment by igr-santos** [comment]
@lpirola fixed problem?
