### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#303]
Pull Request #286

https://sentry.io/nossas-cidades/rebu-website/issues/204410305/

```
TypeError: Cannot read property 'filter' of undefined
  at Object.getMobilization (./app/scripts/Mobilization/MobilizationSelectors.js:6:23)
  at None (./app/modules/widgets/action-creators/async-widget-update.js:7:45)
  at SettingsFieldsPage.addField (./app/modules/widgets/__plugins__/form/pages/settings-fields-page.js:50:4)
  at SettingsFieldsPage.handleAddTextField (./app/modules/widgets/__plugins__/form/pages/settings-fields-page.js:31:9)
...
(18 additional frame(s) were not displayed)
```

**Comment by igr-santos** [comment]
Fixed in https://github.com/ourcities/rebu-client/blob/add/refactor-modules/app/modules/widgets/action-creators/async-widget-update.js#L1, replace selector of module been used
