### ISSUE TITLE
Custom domain view

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#412]
When the url http://329-teste.reboo-staging.org/ is reached the following error is triggered.

```
2017-03-10T17:01:11.251793605Z app[web.1]: TypeError: Cannot read property 'body_font' of undefined
2017-03-10T17:01:11.251838979Z app[web.1]:     at EditorNew.render (/app/build/webpack:/client/mobilizations/widgets/__plugins__/content/components/editor-new/index.js?3946*:45:13)
2017-03-10T17:01:11.251850603Z app[web.1]:     at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:799:1)
2017-03-10T17:01:11.251856355Z app[web.1]:     at ReactCompositeComponentWrapper._renderValidatedComponent (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:822:1)
2017-03-10T17:01:11.251861141Z app[web.1]:     at ReactCompositeComponentWrapper.performInitialMount (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:362:1)
2017-03-10T17:01:11.251865509Z app[web.1]:     at ReactCompositeComponentWrapper.mountComponent (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:258:1)
2017-03-10T17:01:11.251869342Z app[web.1]:     at Object.mountComponent (/app/build/webpack:/~/react-dom/lib/ReactReconciler.js:46:1)
2017-03-10T17:01:11.251873336Z app[web.1]:     at ReactCompositeComponentWrapper.performInitialMount (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:371:1)
2017-03-10T17:01:11.251877698Z app[web.1]:     at ReactCompositeComponentWrapper.mountComponent (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:258:1)
2017-03-10T17:01:11.251881478Z app[web.1]:     at Object.mountComponent (/app/build/webpack:/~/react-dom/lib/ReactReconciler.js:46:1)
2017-03-10T17:01:11.251895919Z app[web.1]:     at ReactCompositeComponentWrapper.performInitialMount (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:371:1)
```

**Comment by lpirola** [comment]
some times, the error change do that:

```
2017-03-10T22:56:53.824983903Z app[web.1]: ::ffff:172.17.0.1 - - [10/Mar/2017:22:56:53 +0000] "GET / HTTP/1.1" - - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
2017-03-10T22:56:53.958752806Z app[web.1]: TypeError: Cannot read property 'header_font' of undefined
2017-03-10T22:56:53.958777795Z app[web.1]:     at EditorOld.render (/app/build/webpack:/client/mobilizations/widgets/__plugins__/content/components/editor-old.js?77c8:120:13)
2017-03-10T22:56:53.958784918Z app[web.1]:     at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:799:1)
2017-03-10T22:56:53.958789969Z app[web.1]:     at ReactCompositeComponentWrapper._renderValidatedComponent (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:822:1)
2017-03-10T22:56:53.958794638Z app[web.1]:     at ReactCompositeComponentWrapper.performInitialMount (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:362:1)
2017-03-10T22:56:53.958799373Z app[web.1]:     at ReactCompositeComponentWrapper.mountComponent (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:258:1)
2017-03-10T22:56:53.958804067Z app[web.1]:     at Object.mountComponent (/app/build/webpack:/~/react-dom/lib/ReactReconciler.js:46:1)
2017-03-10T22:56:53.958822592Z app[web.1]:     at ReactCompositeComponentWrapper.performInitialMount (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:371:1)
2017-03-10T22:56:53.958828772Z app[web.1]:     at ReactCompositeComponentWrapper.mountComponent (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:258:1)
2017-03-10T22:56:53.958833016Z app[web.1]:     at Object.mountComponent (/app/build/webpack:/~/react-dom/lib/ReactReconciler.js:46:1)
2017-03-10T22:56:53.958836757Z app[web.1]:     at ReactCompositeComponentWrapper.performInitialMount (/app/build/webpack:/~/react-dom/lib/ReactCompositeComponent.js:371:1)
```

http://10-meu-rio.reboo-staging.org/

**Comment by gabrielrtakeda** [comment]
Closing for now. If the bug persists, this should be reopened.
