### ISSUE TITLE
Error with engine version node v8.1.1

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#671]
# Description
It needs to fix the nodejs version to a version under than v8.1.1. In the CI, the following error was dispatching:

```
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/code/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:120:20)
gyp ERR! stack     at Request.emit (events.js:210:7)
gyp ERR! stack     at Request.onRequestResponse (/code/node_modules/request/request.js:986:10)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:564:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:453:20)
gyp ERR! stack     at emitOne (events.js:115:13)
```

[See.](https://stackoverflow.com/a/44554067)

**Comment by gabrielrtakeda** [comment]
# Solution
As a temporary solution, I have forked the [kkarczmarczyk/docker-node-yarn](https://github.com/kkarczmarczyk/docker-node-yarn) repository to use the strict version v8.1.0 of node..

### Github repos
- **base:** [kkarczmarczyk/docker-node-yarn](https://github.com/kkarczmarczyk/docker-node-yarn)
- **fork:** [nossas/docker-node-yarn](https://github.com/nossas/docker-node-yarn)

### Docker repos
- **base:** [kkarczmarczyk/node-yarn](https://hub.docker.com/r/kkarczmarczyk/node-yarn/)
- **fork:** [gabrielrtakeda/node-yarn](https://hub.docker.com/r/gabrielrtakeda/node-yarn/)

The docker image using the v8.1.0 of node is tagged in [gabrielrtakeda/node-yarn](https://hub.docker.com/r/gabrielrtakeda/node-yarn/) docker's hub repo.
